version: '3.1'
services:
  web_page:
    build: ./containers/web_page/
    container_name: "web_SSRF"
    networks:
        - my_network
    volumes:
      - ./site:/var/www/html

networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
